export type Employee = {
  employeeId: number;
  name: string;
  email: string;
  departmentId: number;
  designationId: number;
  status: "Active" | "Inactive";
  phone: string;
  address1: string;
  address2: string;
  countryId: number;
  stateId: number;
  cityId: number;
  pincode: string;
  profileImage: FileList;
  joiningDate: string;
  salary: number;
  gender: "Male" | "Female";
  maritalStatus: "Married" | "Unmarried" | "Single" | "Divorce";
};
